import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import logo from '../assets/LogoAmarela.png';
import { ShoppingCart } from "@phosphor-icons/react";
import { useContext, useState } from 'react';
import { AuthContext } from '../Context/Auth';
export function Header() {
    const { authenticated, userLogout } = useContext(AuthContext);
    const [menuOpen, setMenuOpen] = useState(false);
    const handleMenuToggle = () => {
        setMenuOpen(!menuOpen);
    };
    return (_jsx("header", { className: "bg-black-400", children: _jsxs("nav", { className: "mx-auto px-4 py-8 sm:px-6 lg:px-8 flex items-center justify-between", "aria-label": "Global", children: [_jsx("div", { className: "flex items-center", children: _jsxs(Link, { to: "/", className: "mr-6", children: [_jsx("span", { className: "sr-only", children: "Your Company" }), _jsx("img", { className: "h-14 w-auto", src: logo, alt: "Logo Site" })] }) }), _jsxs("div", { className: "hidden lg:flex items-center space-x-10", children: [_jsx(Link, { to: "/", className: "text-lg font-semibold leading-6 text-white", children: "Home" }), _jsx(Link, { to: "/carrinho", className: "text-lg font-semibold leading-6 text-white", children: _jsx(ShoppingCart, { size: 20, color: "#FFF", weight: "bold" }) }), _jsx("div", { className: "font-serif", children: authenticated ? (_jsx("button", { onClick: userLogout, className: "text-lg font-semibold leading-6 text-white cursor-pointer", children: "Sair" })) : (_jsxs(Link, { to: "/login", className: "text-lg font-semibold leading-6 text-white", children: ["Entrar ", _jsx("span", { "aria-hidden": "true", children: "\u2192" })] })) })] }), _jsx("div", { className: "lg:hidden flex items-center", children: _jsx("button", { className: "text-white", onClick: handleMenuToggle, children: _jsx("svg", { className: "h-6 w-6", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16m-7 6h7" }) }) }) }), menuOpen && (_jsxs("div", { className: "lg:hidden flex flex-col gap-4 p-4", children: [_jsx(Link, { to: "/", className: "text-lg font-semibold leading-6 text-white text-center", children: "Home" }), _jsx(Link, { to: "/carrinho", className: "text-lg font-semibold leading-6 text-white text-center", children: _jsx(ShoppingCart, { size: 20, color: "#FFF", weight: "bold" }) }), authenticated ? (_jsx("button", { onClick: userLogout, className: "text-lg font-semibold leading-6 text-white cursor-pointer text-center", children: "Sair" })) : (_jsxs(Link, { to: "/login", className: "text-lg font-semibold leading-6 text-white text-center", children: ["Entrar ", _jsx("span", { "aria-hidden": "true", children: "\u2192" })] }))] }))] }) }));
}
